image: gitpod/workspace-full

tasks:
  - name: Backend
    init: pip install -r backend/requirements.txt
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
  - name: Frontend
    init: cd frontend/react-app && npm install
    command: cd frontend/react-app && npm run dev

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
